### PR TITLE
OFConnectionManager2: send bundle commit reply after processing bundled messages (IND-86)

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: @kenchiang

The bundle commit reply used to be sent after the messages were processed, but
that was broken when I split bundle commit out into a long running task.

### CODE REVIEW

**Comment by rlane** [comment]
OFTest: https://github.com/floodlight/oftest/pull/202

**Comment by kenchiang** [comment]
do we also need to change free_bundle to free the reply if it is set?

**Comment by rlane** [comment]
Discussed with Ken offline. The bundle_t struct does not contain the reply.

SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs24.eng.bigswitch.com/abat/2015.12.11.2334-m.indigo.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vbs24.eng.bigswitch.com/abat/2015.12.11.2334-m.indigo.master/abat.log
/cc @rlane

**Pull request merged**
