### PR TITLE
add latency debug counters to SocketManager

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: @kenchiang

### CODE REVIEW

**Comment by kenchiang** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs21/abat/2015.05.12.0212-m.indigo.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in indigo/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vbs21/abat/2015.05.12.0212-m.indigo.master/abat.log
/cc @rlane

**Comment by rlane** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs21/abat/2015.05.12.1720-m.indigo.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vbs21/abat/2015.05.12.1720-m.indigo.master/abat.log
/cc @rlane

**Pull request merged**
