### PR TITLE
Gentable errors send of_bsn_error messages instead of BAD_REQUEST/EPERM.

### PR DESCRIPTION
**Pull request by kenchiang**
Reviewer: @rlane 

Depends on of_bsn_error https://github.com/floodlight/loxigen/pull/441.

### CODE REVIEW

**Comment by kenchiang** [comment]
I'll need to update submodules/loxigen-artifacts once floodlight/loxigen#441 is merged.

**Comment by kenchiang** [comment]
I've updated submodules/loxigen-artifacts; please review when you have some time.  Thanks.

**Comment by rlane** [comment]
I suggest doing the copy from a string to the of_desc_str_t array inside the function to simplify the caller. In the future I think we'll want a printf-style version of this function too.

**Comment by kenchiang** [comment]
Pushed a new commit; please take a look.  Thanks.

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs24.eng.bigswitch.com/abat/2015.12.04.2243-m.indigo.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in indigo/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vbs24.eng.bigswitch.com/abat/2015.12.04.2243-m.indigo.master/abat.log
/cc @rlane

**Comment by kenchiang** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs24.eng.bigswitch.com/abat/2015.12.04.2305-m.indigo.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vbs24.eng.bigswitch.com/abat/2015.12.04.2305-m.indigo.master/abat.log
/cc @rlane

**Pull request merged**
