### PR TITLE
Rework Configuration module to use cjson_util.

### PR DESCRIPTION
**Pull request by kenchiang**
Reviewer: @jnealtowns 
Clean up memory leaks in unit test.

### CODE REVIEW

**Comment by kenchiang** [comment]
Sorry, please hold off on reviewing this pull request; I've found a bug where the config file doesn't get parsed.  Let me fix that first.

**Comment by kenchiang** [comment]
I've pushed a new commit to address the previously mentioned bug.  Please take a look.  Thanks.

**Comment by kenchiang** [comment]
ping @jnealtowns

**Comment by jnealtowns** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs24.eng.bigswitch.com/abat/2016.11.04.1707-m.indigo.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in indigo/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vbs24.eng.bigswitch.com/abat/2016.11.04.1707-m.indigo.master/abat.log
/cc @rlane

**Comment by kenchiang** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs26.eng.bigswitch.com/abat/2016.11.04.1743-m.indigo.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vbs26.eng.bigswitch.com/abat/2016.11.04.1743-m.indigo.master/abat.log
/cc @rlane

**Pull request merged**
