### PR TITLE
OFConnectionManager2: fix config file for INDIGO_CXN_PROTO_UNIX

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: @kenchiang

### CODE REVIEW

**Comment by kenchiang** [comment]
sorry you had to fix those obvious mistakes.  should we add a unit test for config file parsing?

**Comment by kenchiang** [comment]
anyway the fixes look good.  self-ack when ready.  thanks.

**Comment by rlane** [comment]
I added support for the "local" field, can you take another look?

**Comment by kenchiang** [comment]
looks good; self-ack when ready.  thanks.

**Comment by rlane** [comment]
Thanks for the review.

SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs26.eng.bigswitch.com/abat/2016.07.19.1902-m.indigo.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vbs26.eng.bigswitch.com/abat/2016.07.19.1902-m.indigo.master/abat.log
/cc @rlane

**Pull request merged**
