### PR TITLE
add generic stats requests for histograms

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: @harshsin 

These changes add two new generic stats requests, "histogram" to retrieve a single histogram and "histograms" for a list of all histograms.

### CODE REVIEW

**Comment by harshsin** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs24.eng.bigswitch.com/abat/2016.04.12.1952-m.indigo.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in indigo/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vbs24.eng.bigswitch.com/abat/2016.04.12.1952-m.indigo.master/abat.log
/cc @rlane

**Comment by rlane** [comment]
ABAT-RETRY

**Comment by rlane** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs26.eng.bigswitch.com/abat/2016.04.12.2022-m.indigo.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in indigo/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vbs26.eng.bigswitch.com/abat/2016.04.12.2022-m.indigo.master/abat.log
/cc @rlane

**Comment by rlane** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs25.eng.bigswitch.com/abat/2016.04.12.2052-m.indigo.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vbs25.eng.bigswitch.com/abat/2016.04.12.2052-m.indigo.master/abat.log
/cc @rlane

**Pull request closed without merging**
