### PR TITLE
Subbundle start/finish

### PR DESCRIPTION
**Pull request by kenchiang**
Reviewer: @poolakiran @shudongz 
Extend subbundle infrastructure so that registered functions can be called before and after subbundles are processed
Add start and finish operations to gentables, and provide functions to invoke those operations

### CODE REVIEW

**Comment by shudongz** [comment]
The new start/finish ops in gentable_ops are good. It's not clear if subbundle registration is required and, if so, what the interfaces look like.

**Comment by kenchiang** [comment]
Subbundle registration is required so that the appropriate subbundle start and finish functions are invoked.  Please see the unit test for an (admittedly lame) example.

**Comment by kenchiang** [comment]
For instance, assume we have a gentable for which we want to collect all operations (adds and deletes) in a given bundle, and a number of other gentables and flow tables about which we do not care.
We can write a subbundle designator that switches on the object_id of the of_object_t, and extracts the table_id in case of OF_BSN_GENTABLE_ENTRY_ADD and OF_BSN_GENTABLE_ENTRY_DELETE.  If the table_id is that of gentable A (the gentable we care about), then designate that of_object to belong to subbundle 0.  For all other of_objects, we designate those to subbundle 1.
We also create subbundle_start and subbundle_finish functions for subbundle 0.
Finally we register everything by calling indigo_cxn_subbundle_set2 with num_subbundles=2, degnator=the designator we wrote above, comparators=NULL, starts={subbundle_start_0,NULL}, and finishes={subbundle_finish_0,NULL}.
The infrastructure should call subbundle_start_0 before processing any gentable A objects, and subbundle_finish_0 after processing all gentable A objects.

**Comment by poolakiran** [comment]
Please document the relation between the subbundle start/stop and gentbale start/stop. Otherwise LGTM.

**Comment by shudongz** [comment]
I got what I wanted, thanks!

**Pull request merged**
